config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # resources
  resources :games, only: %i[ index ]

  # single entity resources
  resource :profile, only: %i[ show ]
  resource :leaderboard, only: %i[ show ]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Games index</h1>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="relative">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= render "shared/navigation" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/leaderboards/show.html.erb
<h1>Leaderboard</h1>

app/views/profiles/show.html.erb
<h1>Profile</h1>

app/views/shared/_navigation.html.erb
<div class="fixed inset-x-0 top-5 z-50">
  <div class="max-w-xs mx-auto">
    <ul class="flex justify-center align-center bg-white rounded-full shadow-md py-1">
      <li class="rounded-full px-3 py-2">
        <%= link_to "Home", root_path, class: "text-sm block text-green-600#{" active" if current_page?(root_path)}" %>
      </li>
      <li class="rounded-full px-3 py-2">
        <%= link_to "Games", games_path, class: "text-sm block text-green-600#{" active" if current_page?(games_path)}" %>
      </li>
      <li class="rounded-full px-3 py-2">
        <%= link_to "Profile", profile_path, class: "text-sm block text-green-600#{" active" if current_page?(profile_path)}" %>
      </li>
      <li class="rounded-full px-3 py-2">
        <%= link_to "Leaderboard", leaderboard_path, class: "text-sm block text-green-600#{" active" if current_page?(leaderboard_path)}" %>
      </li>
    </ul>
  </div>
</div>